/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface VaultMetaProviderInterface extends utils.Interface {
  functions: {
    "_tokenURI()": FunctionFragment;
    "getTokenURI(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "_tokenURI" | "getTokenURI"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "_tokenURI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTokenURI",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "_tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenURI",
    data: BytesLike
  ): Result;

  events: {};
}

export interface VaultMetaProvider extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VaultMetaProviderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _tokenURI(overrides?: CallOverrides): Promise<[string]>;

    getTokenURI(
      vault_address: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  _tokenURI(overrides?: CallOverrides): Promise<string>;

  getTokenURI(
    vault_address: string,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    _tokenURI(overrides?: CallOverrides): Promise<string>;

    getTokenURI(
      vault_address: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    _tokenURI(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenURI(
      vault_address: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _tokenURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTokenURI(
      vault_address: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
