/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Erc20QiStablecoin__factory } from "./Erc20QiStablecoin__factory";
export { Erc20Stablecoin__factory } from "./Erc20Stablecoin__factory";
