/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAToken } from "./IAToken";
export type { IAaveIncentivesController } from "./IAaveIncentivesController";
export type { IERC20 } from "./IERC20";
export type { ILendingPool } from "./ILendingPool";
export type { IStablecoin } from "./IStablecoin";
export type { IStakingRewards } from "./IStakingRewards";
export type { IUniswapV2Pair } from "./IUniswapV2Pair";
export type { IVaultMetaProvider } from "./IVaultMetaProvider";
export type { IVaultMetaRegistry } from "./IVaultMetaRegistry";
