/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface AutoCompounderInterface extends utils.Interface {
  functions: {
    "autoCompound()": FunctionFragment;
    "lastExecuted()": FunctionFragment;
    "resolver()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "autoCompound" | "lastExecuted" | "resolver"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "autoCompound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastExecuted",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resolver", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "autoCompound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolver", data: BytesLike): Result;

  events: {};
}

export interface AutoCompounder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AutoCompounderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    autoCompound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lastExecuted(overrides?: CallOverrides): Promise<[BigNumber]>;

    resolver(
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { execPayload: string }>;
  };

  autoCompound(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lastExecuted(overrides?: CallOverrides): Promise<BigNumber>;

  resolver(
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { execPayload: string }>;

  callStatic: {
    autoCompound(overrides?: CallOverrides): Promise<void>;

    lastExecuted(overrides?: CallOverrides): Promise<BigNumber>;

    resolver(
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { execPayload: string }>;
  };

  filters: {};

  estimateGas: {
    autoCompound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lastExecuted(overrides?: CallOverrides): Promise<BigNumber>;

    resolver(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    autoCompound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lastExecuted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    resolver(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
