/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20QiStablecoinCamwbtcSol from "./erc20QiStablecoin-camwbtc.sol";
export type { erc20QiStablecoinCamwbtcSol };
import type * as erc20QiStablecoinWbtcSol from "./erc20QiStablecoin-wbtc.sol";
export type { erc20QiStablecoinWbtcSol };
import type * as erc20StablecoinCamWbtcSol from "./erc20Stablecoin-cam-wbtc.sol";
export type { erc20StablecoinCamWbtcSol };
import type * as erc20StablecoinWbtcSol from "./erc20Stablecoin-wbtc.sol";
export type { erc20StablecoinWbtcSol };
