/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Uni, UniInterface } from "../../../contracts/camAave.sol/Uni";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "swapExactTokensForTokens",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Uni__factory {
  static readonly abi = _abi;
  static createInterface(): UniInterface {
    return new utils.Interface(_abi) as UniInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Uni {
    return new Contract(address, _abi, signerOrProvider) as Uni;
  }
}
