/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IMyVault, IMyVaultInterface } from "../../contracts/IMyVault";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "to",
        type: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMyVault__factory {
  static readonly abi = _abi;
  static createInterface(): IMyVaultInterface {
    return new utils.Interface(_abi) as IMyVaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMyVault {
    return new Contract(address, _abi, signerOrProvider) as IMyVault;
  }
}
