/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVaultMetaRegistry,
  IVaultMetaRegistryInterface,
} from "../../../contracts/interfaces/IVaultMetaRegistry";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "vault_address",
        type: "address",
      },
    ],
    name: "getMetaProvider",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class IVaultMetaRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultMetaRegistryInterface {
    return new utils.Interface(_abi) as IVaultMetaRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVaultMetaRegistry {
    return new Contract(address, _abi, signerOrProvider) as IVaultMetaRegistry;
  }
}
