/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVaultMetaProvider,
  IVaultMetaProviderInterface,
} from "../../../contracts/interfaces/IVaultMetaProvider";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getBaseURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "vault_address",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getTokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class IVaultMetaProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultMetaProviderInterface {
    return new utils.Interface(_abi) as IVaultMetaProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVaultMetaProvider {
    return new Contract(address, _abi, signerOrProvider) as IVaultMetaProvider;
  }
}
