/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AutoCompounder__factory } from "./AutoCompounder__factory";
export { CamToken__factory } from "./CamToken__factory";
