/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20QiStablecoin } from "./Erc20QiStablecoin";
export type { Erc20Stablecoin } from "./Erc20Stablecoin";
