/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface IMasterChefInterface extends utils.Interface {
  functions: {
    "pending(uint256,address)": FunctionFragment;
    "userInfo(uint256,address)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "pending" | "userInfo"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "pending",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userInfo",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "pending", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userInfo", data: BytesLike): Result;

  events: {};
}

export interface IMasterChef extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMasterChefInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    pending(
      nr: BigNumberish,
      who: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    userInfo(
      nr: BigNumberish,
      who: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  pending(
    nr: BigNumberish,
    who: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userInfo(
    nr: BigNumberish,
    who: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  callStatic: {
    pending(
      nr: BigNumberish,
      who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userInfo(
      nr: BigNumberish,
      who: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    pending(
      nr: BigNumberish,
      who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userInfo(
      nr: BigNumberish,
      who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    pending(
      nr: BigNumberish,
      who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userInfo(
      nr: BigNumberish,
      who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
