/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20QiStablecoinCamwbtcSol from "./erc20QiStablecoin-camwbtc.sol";
export * as erc20QiStablecoinWbtcSol from "./erc20QiStablecoin-wbtc.sol";
export * as erc20StablecoinCamWbtcSol from "./erc20Stablecoin-cam-wbtc.sol";
export * as erc20StablecoinWbtcSol from "./erc20Stablecoin-wbtc.sol";
