/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelinContracts340 from "./openzeppelin-contracts-3.4.0";
export type { openzeppelinContracts340 };
